# Generated by Django 4.0.2 on 2022-03-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_group_course_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='First_Name'),
        ),
    ]
